spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:2345/todo_list
    username: postgres
    password: 1234
# swagger-ui custom path
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  show-actuator: true